controller_manager:
  ros__parameters:
    update_rate: 50
    
    # Joint Trajectory Controller
    fr5_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    fr5_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

fr5_arm_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6

  
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


fr5_gripper_controller:
  ros__parameters:
    joints:
      - Slider_driver

    command_interfaces:
      - position
    
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true