# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    my_group_joint_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    my_end_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

my_group_joint_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
my_end_controller:
  ros__parameters:
    joint: Slider_driver
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity